---
blank_issues_enabled: false
contact_links:
  - name: Creating REST APIs Community Support
    url: https://github.com/developer-academy-unina/Workshop-Creating-REST-API/discussions
    about: Please ask and answer questions here.
